# Generated by Django 2.1.4 on 2018-12-18 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0003_auto_20181218_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='article',
        ),
        migrations.AddField(
            model_name='tag',
            name='article',
            field=models.ManyToManyField(blank=True, null=True, related_name='tags', to='articles.Article', verbose_name='Article'),
        ),
    ]
