# Generated by Django 2.1.4 on 2018-12-18 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_auto_20181218_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='created_date',
            field=models.CharField(default='None', max_length=50, verbose_name='CreationDate'),
        ),
    ]
