# Generated by Django 2.1.4 on 2018-12-24 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0021_article_comments_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userlikedarticles',
            name='user',
        ),
        migrations.AddField(
            model_name='useraccount',
            name='likeArticles',
            field=models.ManyToManyField(to='articles.Article', verbose_name='Liked articles'),
        ),
        migrations.DeleteModel(
            name='UserLikedArticles',
        ),
    ]
